const { Dog } = require('../models');

const dogData = [
    {
        id: 1,
        name: 'Tara',
        age: 1,
        breed: 'Rhodesian Ridgeback',
        size: 'Large',
        sex: 'female',
        color: 'Brown',
        description: 'Tara is a very loving and energetic pup! Hates children',
        for_sale: true,
        media_id: 1,
        user_id: 1,
    },
    {
        id: 2,
        name: 'Fido',
        age: 1,
        breed: 'Corgi',
        size: 'Small',
        sex: 'male',
        color: 'Blonde',
        description: 'Hates children but really loves cats',
        for_sale: true,
        media_id: 2,
        user_id: 2,
    },
    {
        id: 3,
        name: 'Bingo',
        age: 1,
        breed: 'Husky',
        size: 'Large',
        sex: 'male',
        color: 'Grey',
        description: 'Bingo Was his name-o',
        for_sale: true,
        media_id: 3,
        user_id: 3,
    },
    {
        id: 4,
        name: 'Zara',
        age: 1,
        breed: 'German Shepard',
        size: 'Large',
        sex: 'female',
        color: 'Brown',
        description: 'Zara is a healthy baby girl',
        for_sale: true,
        media_id: 4,
        user_id: 4,
    },
    {
        id: 5,
        name: 'Nala',
        age: 1,
        breed: 'Rhodesian Ridgeback',
        size: 'Large',
        sex: 'female',
        color: 'Brown',
        description: 'Nala is a beautiful girl',
        for_sale: true,
        media_id: 5,
        user_id: 5,
    },
    {
        id: 6,
        name: 'Zipp',
        age: 1,
        breed: 'Border Collie',
        size: 'Medium',
        sex: 'male',
        color: 'Black',
        description: 'Zipp zapp patty wack',
        for_sale: true,
        media_id: 6,
        user_id: 6,
    },
    {
        id: 7,
        name: 'Pinkie',
        age: 1,
        breed: 'Great Dane',
        size: 'Large',
        sex: 'female',
        color: 'Grey',
        description: 'Reading Rainbow Pink Pink Pink',
        for_sale: true,
        media_id: 7,
        user_id: 7,
    },
    {
        id: 8,
        name: 'Scout',
        age: 1,
        breed: 'Beagle',
        size: 'Medium',
        sex: 'male',
        color: 'Brown',
        description: 'Scout can see you...',
        for_sale: true,
        media_id: 8,
        user_id: 8,
    },

];

const seedDogs = () => Dog.bulkCreate(dogData);

module.exports = seedDogs;